### ISSUE TITLE
Able to create post with non-existing user.

### ISSUE THREAD

**Issue by 1martinkarlsen** [AlexanderFalk/hackernews_backend#46]
Seems like I'm able to create a story, using the simulator post API, with a non-existing user.
Tried this:

```
{"post_title": "Y Combinator", 
 "post_text": "test text", 
 "hanesst_id": 9999999992, 
 "post_type": "comment", 
 "post_parent": -1, 
 "username": "JonasSimonsen", 
 "pwd_hash": "b0f3dc043a9c5c05f67651a8c9108b4c2b98e7246b2eea14cb204295", 
 "post_url": "http://ycombinator.com"}
```

Which resulted in this:
```
{
    "post_title": "Y Combinator",
    "post_text": "test text",
    "hanesst_id": 1410065400,
    "post_type": "comment",
    "post_parent": -1,
    "username": "JonasSimonsen",
    "pwd_hash": "b0f3dc043a9c5c05f67651a8c9108b4c2b98e7246b2eea14cb204295",
    "post_url": "http://ycombinator.com"
}
```

Pretty sure that JonasSimonsen doesn't exist in the system, but still I'm able to create stories.

**Comment by dbdness** [comment]
Thanks for the issue! But I'm not sure this is an official requirement? If a user doesn't exist, we add him as a user the first time he posts. This is only done through the simulator route, and not elsewhere in the API. We knew Helge would post a lot of users, and that's why we did it this way.
